global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'backend_api'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['backend-api:3000']

  - job_name: 'frontend_dashboard'
    metrics_path: '/'
    static_configs:
      - targets: ['frontend-dashboard:8001']
