global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'frontend_golden_signals'
    metrics_path: '/'
    static_configs:
      # Cible locale pour tester le Streamlit depuis Grafana/Prometheus (qui tournent en Docker)
      - targets: ['host.docker.internal:8001']
