global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'backend_golden_signals'
    metrics_path: '/metrics'
    static_configs:
      # Ajuste cette adresse selon si tu lances le projet avec Docker ('host.docker.internal:8000') ou en local ('localhost:8000')
      - targets: ['host.docker.internal:8000']
